basePath: /sample
info:
  title: POC
  version: 1.0.0
  x-ibm-name: poc-cbi2
paths:
  /sample:
    delete: &id001
      responses:
        '200':
          description: success
          schema:
            type: object
        '400':
          $ref: '#/responses/errorResponse'
        '401':
          $ref: '#/responses/errorResponse'
        '500':
          $ref: '#/responses/errorResponse'
    get: *id001
    post: *id001
  /test:
    get: *id001
    post: *id001
responses:
  errorResponse:
    description: Sample error response structure
    schema:
      properties:
        ErrorResponse:
          properties:
            additionalinfo:
              properties:
                excepCode:
                  type: string
                excepMetaData:
                  type: string
                excepText:
                  type: string
              type: object
            metadata:
              properties:
                status:
                  properties:
                    code:
                      type: string
                    desc:
                      type: string
                  type: object
              type: object
          type: object
      type: object
schemes:
- https
security:
- client_id: []
  client_secret: []
securityDefinitions:
  client_id:
    in: header
    name: X-IBM-Client-Id
    type: apiKey
    x-key-type: client_id
  client_secret:
    in: header
    name: X-IBM-Client-Secret
    type: apiKey
    x-key-type: client_secret
swagger: '2.0'
x-ibm-configuration:
  application-authentication:
    certificate: true
  application-authentication-source:
  - header
  assembly:
    execute:
    - jws-verify:
        version: 1.0.0
    - jwe-decryption:
        version: 1.0.0
    - invoke:
        follow-redirects: false
        header-control:
          type: blocklist
          values: []
        inject-proxy-headers: true
        parameter-control:
          type: allowlist
          values: []
        target-url: $(target-url)
        timeout: 60
        title: invoke
        verb: keep
        version: 2.0.0
    - jwe-encryption:
        version: 1.0.0
  cors:
    enabled: true
  enforced: true
  gateway: datapower-api-gateway
  phase: realized
  properties:
    dec-key:
      value: testKey
    enc-alg:
      value: RSA1_5
    enc-cert:
      value: testKey
    enc-dec-pattern:
      value: hybrid
    enc-dec-type:
      value: body
    target-url:
      description: URL of the proxy policy
      encoded: false
      value: http://httpbin.org/post
  testable: true
  type: rest
